config/routes.rb
Labohp::Application.routes.draw do
  root "main_pages#home"

  resources :users do
    member do
      get :following, :followers, :activate
    end
    collection do
      get :thanks_for_signup
    end
  end
  match "/introduction", to: "main_pages#introduction", via: "get"
  match "/signup", to: "users#new", via: "get"
  resources :sessions, only: [:new, :create, :destroy]
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  resources :microposts , only: [:create, :destroy, :edit, :update] do
    member do
      post :likes
      delete :dislikes
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :products do
    collection do
      get :computer, :literature
    end
    
    member do
      get :create_micropost 
      post :wanna_read
      delete :not_wanna_read
    end
  end

end

app/views/shared/_current_user_stats.html.haml
- @user = current_user
%ul.stats
  %li
    / %a{ href: following_user_path(@user) }
    %strong#current_following.stat
      ="フォロー  " + @user.followed_users.count.to_s
  %li
    / %a{ href: followers_user_path(@user) }
    %strong#current_followers.stat
      = "フォロワー  " + @user.followers.count.to_s

app/views/shared/_error_messages.html.haml
- if object.errors.any?
  #error_explanation
    %p エラーがあります！
    %ul
    - object.errors.full_messages.each do |msg|
      %li
        *
        = msg

app/views/shared/_feed.html.haml
/ ol要素はajaxに関連しているので削除しないこと
- if @feed_items.any?
  %ol.microposts
    = render partial: "shared/feed_item", collection: @feed_items
- else 
  %p 現在フィードはありません

app/views/shared/_feed_item.html.haml
/ li要素はajaxに関連しているので削除しないこと
%li.feed_item{id: feed_item.id}
  .row
    .left_content.col-xs-2
      .user
        = link_to gravatar_for(feed_item.user), feed_item.user
      .nick_name
        = link_to feed_item.user.nickname, feed_item.user
      .timestamp
        Posted #{time_ago_in_words(feed_item.created_at)} ago.
    .right_content.col-xs-10
      .product
        %p=link_to "#{feed_item.product.title}(#{feed_item.product.genre})", product_path(feed_item.product.id)
      .content
        = wrap(feed_item.content)
      %span.likes_block
        = render partial: "microposts/likes_form", locals: {feed_item: feed_item }
        %span.likes{ id: feed_item.id }
          = "#{feed_item.reputation_for(:likes).to_i} いいね！"
      %span.wanna_read_block
        = render partial: "products/wanna_read_form", locals: {feed_item: feed_item }
        %span.wanna_read{ class: feed_item.product.id }
          = "#{feed_item.product.reputation_for(:wanna_read).to_i} 読みたい！"
      %span.delete_block
        - unless current_user == nil
          -if current_user == feed_item.user || current_user.admin?
            =link_to "投稿を編集", edit_micropost_path(feed_item.id)
            =link_to "投稿を削除", micropost_path(feed_item.id), method: :delete, data: { confirm: "本当に削除してもよろしいですか？" }

app/views/shared/_genre_links.html.haml
%h4
  %i.glyphicon.glyphicon-search 
  %p ジャンル
%ul
  %li= link_to "文学・評論", literature_products_path
  %li= link_to "人文・思想", "#"
  %li= link_to "社会・政治", "#"
  %li= link_to "ノンフィクション", "#"
  %li= link_to "歴史・地理", "#"
  %li= link_to "ビジネス・経済", "#"
  %li= link_to "投資・金融・会社経営", "#"
  %li= link_to "科学・テクノロジー", "#"
  %li= link_to "医学・薬学", "#"
  %li= link_to "コンピュータ・IT", computer_products_path
  %li= link_to "アート・建築・デザイン", "#"
  %li= link_to "趣味・実用", "#"
  %li= link_to "スポーツ・アウトドア", "#"
  %li= link_to "資格・検定・就職", "#"
  %li= link_to "暮らし・健康・子育て", "#"
  %li= link_to "旅行ガイド・マップ", "#"
  %li= link_to "語学・辞事典・年鑑", "#"
  %li= link_to "教育・学参・受験", "#"
  %li= link_to "絵本・児童書", "#"
  %li= link_to "コミック・ラノベ・BL", "#"
  %li= link_to "ライトノベル", "#"
  %li= link_to "タレント写真集", "#"
  %li= link_to "ゲーム攻略・ゲームブック", "#"
  %li= link_to "エンターテイメント", "#"
  %li= link_to "新書・文庫", "#"
  %li= link_to "雑誌", "#"
  %li= link_to "楽譜・スコア・音楽書", "#"

  / %li= link_to "文学", literature_products_path
  / %li= link_to "恋愛", love_products_path
  / %li= link_to "歴史", history_products_path
  / %li= link_to "推理", mystery_products_path
  / %li= link_to "ファンタジー", fantasy_products_path
  / %li= link_to "SF", sf_products_path
  / %li= link_to "ホラー", horror_products_path
  / %li= link_to "コメディ", comedy_products_path
  / %li= link_to "冒険", adventure_products_path
  / %li= link_to "学園", academy_products_path
  / %li= link_to "戦記", millitary_products_path
  / %li= link_to "童話", fairy_tail_products_path
  / %li= link_to "詩",  poem_products_path
  / %li= link_to "エッセイ", essay_products_path
  / %li= link_to "リプレイ", replay_products_path
  / %li= link_to "その他", others_products_path

app/views/shared/_home_notice.html.haml
.home_notice
  %h5 
    %ul
      %li
        %i.glyphicon.glyphicon-bullhorn
      %li
        %p お知らせ
  .notice_content
    %ul
      %li 最新のお知らせはありません

app/views/shared/_micropost_form.html.haml
= form_for(@micropost) do |f|
  = render 'shared/error_messages', object: f.object
  .field
    = f.text_area :content, placeholder: "Compose new micropost..."
  = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_micropost_number.html.haml
/ 現在未使用
#micropost_number
  %h4
    %ul
      %li
        %h5
          %i.glyphicon.glyphicon-pencil
      %li
        読んだ作品:
      %li= current_user.microposts.count

app/views/shared/_not_signed_in_home.html.haml
= render "shared/home_notice"

#recent_micropost 
  %h4
    %i.glyphicon.glyphicon-book
      最近投稿された感想

  = render "shared/feed"
  = will_paginate @feed_items, :renderer => BootstrapPagination::Rails

app/views/shared/_recent_feed.html.haml
/ ol要素はajaxに関連しているので削除しないこと
- if @recent_feed_items.any?
  %ol.microposts
    = render partial: "shared/feed_item", collection: @recent_feed_items
- else 
  %p 現在フィードはありません

app/views/shared/_signed_in_home.html.haml
= render "shared/home_notice"
- if @feed_items.any?
  #follower_micropost
    %h4 フォロー中ユーザーの新着投稿
    = render "shared/feed"
    = will_paginate @feed_items, :renderer => BootstrapPagination::Rails
- else
  #follower_micropost
    %h4 フォロー中ユーザーの投稿はありません
- if @recent_feed_items.any?
  #recent_micropost
    %h4 最近投稿された感想
    = render "shared/recent_feed"
    = will_paginate @recent_feed_items, :renderer => BootstrapPagination::Rails
- else
  #recent_micropost

app/views/shared/_stats.html.haml
%ul.stats
  %li
    / %a{ href: following_user_path(@user) }
    %strong#following.stat
      ="フォロー  " + @user.followed_users.count.to_s
  %li
    / %a{ href: followers_user_path(@user) }
    %strong#followers.stat
      = "フォロワー  " + @user.followers.count.to_s

app/views/shared/_user_actions.html.haml
%section
  = button_to products_path, method: :get , class: "btn btn-lg btn-default" do
    %i.glyphicon.glyphicon-pencil
    %p 感想の投稿はこちら
%section
  = button_to edit_user_path(current_user), method: :get , class: "btn btn-lg btn-default" do
    %i.glyphicon.glyphicon-user
    %p ユーザー情報の管理はこちら
%section
  = button_to user_path(current_user), method: :get , class: "btn btn-lg btn-default" do
    %i.glyphicon.glyphicon-edit
    %p 投稿内容の管理はこちら

app/views/shared/_user_info.html.haml
%ul
  %li
    %a{href: user_path(current_user)}
    = gravatar_for current_user
  %li
    %h5
      = current_user.nickname
      =render "shared/current_user_stats"