config/routes.rb
Labohp::Application.routes.draw do
  root "main_pages#home"

  resources :users do
    member do
      get :following, :followers, :activate
    end
    collection do
      get :thanks_for_signup
    end
  end
  match "/introduction", to: "main_pages#introduction", via: "get"
  match "/signup", to: "users#new", via: "get"
  resources :sessions, only: [:new, :create, :destroy]
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  resources :microposts , only: [:create, :destroy, :edit, :update] do
    member do
      post :likes
      delete :dislikes
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :products do
    collection do
      get :computer, :literature
    end
    
    member do
      get :create_micropost 
      post :wanna_read
      delete :not_wanna_read
    end
  end

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
  belongs_to :user
  belongs_to :product

  default_scope { order('created_at DESC') }

  validates :user_id,:product_id, presence: true

  validates :content, 
    presence: true,
    length:{ maximum: 400 } #人が１分で読める量の限界。最大文字数は今後も検討

  has_reputation :likes, source: :user, aggregated_by: :sum

  def self.from_users_followed_by(user)
    followed_user_ids = user.followed_user_ids
    where("user_id IN (:followed_user_ids) OR user_id = :user_id",
          followed_user_ids: followed_user_ids, user_id: user)
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :signed_in_user, only: [:create, :edit, :destroy, :likes, :dislikes]
  before_action :correct_user,   only: [:edit, :destroy]
  before_action :set_micropost,  only: [:edit, :update, :likes, :dislikes]

  def index
  end

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      flash[:failure] = "Micropost created error!"
      redirect_to root_url
    end
  end

  def edit
    @product = @micropost.product
  end

  def update

    if @micropost.update_attributes(micropost_params)
      flash[:success] = "投稿の編集が完了しました"
      redirect_to root_url
    else
      @product = @micropost.product
      render "edit"
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  def likes
    redeirect_to root_url if @micropost.user == current_user
    @micropost.add_evaluation(:likes, 1, current_user)
    @likes_num = @micropost.reputation_for(:likes).to_i
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def dislikes
    redeirect_to root_url if @micropost.user == current_user
    @micropost.delete_evaluation(:likes, current_user)
    @likes_num = @micropost.reputation_for(:likes).to_i
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  private
    def micropost_params
      params.require(:micropost).permit(:content, :product_id, :user_id)
    end

    def correct_user
      @micropost = Micropost.find_by(id: params[:id])
      unless current_user.admin? || current_user?(@micropost.user)
        redirect_to root_path
      end
    end

    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    def set_product
      @product = Product.find(params[:id])
      @microposts = @product.microposts.paginate(page: params[:page])
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
  def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
end

app/views/microposts/_ajax_dislikes.html.haml
= form_tag(dislikes_micropost_path(@micropost.id), method: :delete,remote: true) do
  = button_tag( class: "btn btn-white btn-xs dislikes-button", id: @micropost.id ) do
    = content_tag :span, "いいね！を削除"

app/views/microposts/_ajax_likes.html.haml
= form_tag(likes_micropost_path(@micropost.id), remote: true) do
  = button_tag( class: "btn btn-nav btn-xs likes-button", id: @micropost.id ) do
    = content_tag :span, "いいね！", class: "glyphicon glyphicon-thumbs-up"

app/views/microposts/_dislikes.html.haml
= form_tag(dislikes_micropost_path(feed_item.id), method: :delete,remote: true) do
  = button_tag( class: "btn btn-white btn-xs dislikes-button", id: feed_item.id ) do
    = content_tag :span, "いいね！を削除"

app/views/microposts/_likes.html.haml
= form_tag(likes_micropost_path(feed_item.id),remote: true) do
  = button_tag( class: "btn btn-nav btn-xs likes-button", id: feed_item.id ) do
    = content_tag :span, "いいね！", class: "glyphicon glyphicon-thumbs-up"

app/views/microposts/_likes_form.html.haml
- unless current_user == nil
  - unless current_user?(feed_item.user)
    .likes_form{ id: feed_item.id }
      - if current_user.liked?(feed_item)
        = render partial: "microposts/dislikes", locals: {feed_item: feed_item}
      - else
        = render partial: "microposts/likes", locals: {feed_item: feed_item}

app/views/microposts/_micropost.html.haml
/ 現在未使用？
%li{id: feed_item.id}
  %span.content<
    = feed_item.content
  %span.timestamp<
    Posted
    = time_ago_in_words(feed_item.created_at)
    ago
  = delete_item(feed_item)
  - unless current_user?(feed_item.user)
    #likes_form
      - if current_user.liked?(feed_item)
        = render partial: "microposts/dislikes", locals: { feed_item: feed_item }
      - else
        = render partial: "microposts/likes", locals: { feed_item: feed_item }
  = "#{feed_item.reputation_for(:likes).to_i} いいね！"
  / - if current_user?(micropost.user)
  /   = link_to "delete",micropost, method: :delete,data: {confirm:"You sure?"}, title: micropost.content

app/views/microposts/dislikes.js.haml
$(".likes_form","li##{@micropost.id}").html("#{escape_javascript render 'microposts/ajax_likes'}");
$(".likes","li##{@micropost.id}").html('#{@likes_num} いいね!');

app/views/microposts/edit.html.haml
- provide :title, "感想を編集する"
#create_micropost_page
  %h3="#{@product.title}の感想を編集"
  = form_for @micropost do |f|
    = render "shared/error_messages", object: f.object
    .field
      %table
        %tr.title
          %th.title
            作品名
          %td.title
            %h4 
            = @product.title
        %tr.content
          %th
            = f.label :content, "投稿内容"
          %td
            = f.text_area :content, :size => "50x7"
            %p ※400字以内
      = f.hidden_field :product_id, value: @product.id
      = f.hidden_field :user_id, value: current_user.id
      = f.submit "編集する", class: "btn btn-large btn-primary"

app/views/microposts/likes.js.haml
$(".likes_form","li##{@micropost.id}").html("#{escape_javascript render 'microposts/ajax_dislikes'}");
$(".likes","li##{@micropost.id}").html('#{@likes_num} いいね!');