config/routes.rb
Labohp::Application.routes.draw do
  root "main_pages#home"

  resources :users do
    member do
      get :following, :followers, :activate
    end
    collection do
      get :thanks_for_signup
    end
  end
  match "/introduction", to: "main_pages#introduction", via: "get"
  match "/signup", to: "users#new", via: "get"
  resources :sessions, only: [:new, :create, :destroy]
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  resources :microposts , only: [:create, :destroy, :edit, :update] do
    member do
      post :likes
      delete :dislikes
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :products do
    collection do
      get :computer, :literature
    end
    
    member do
      get :create_micropost 
      post :wanna_read
      delete :not_wanna_read
    end
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  has_many :microposts, dependent: :destroy
  has_many :users, through: :microposts

  default_scope { order(created_at: :desc) }

  validates :title,
    presence: true,
    uniqueness: true,
    length: { maximum: 100 }

  validates :genre,
    presence: true

  validates :link,
    uniqueness: {case_sensitive: true},
    length: { maximum: 300 },
    allow_blank: true,
    format: URI::regexp(%w(http https))

  has_reputation :wanna_read, source: :user, aggregated_by: :sum
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :signed_in_user, only: [:new, :create, :edit, :update, :destroy, :create_micropost, :wanna_read, :not_wanna_read]
  before_action :admin_user,     only: [:destroy, :edit, :update]
  before_action :set_product,    only: [:show, :edit, :update, :create_micropost, :wanna_read, :not_wanna_read]

  #ransackを使って作品を検索した後、ページネーションを使用
  def index
    @search = Product.search(params[:q])#search_formから値を取得
    @products = @search.result.paginate(page: params[:page])
  end

  def search_product
    @search = Product.search(params[:q])#search_formから値を取得
    @products = @search.result.paginate(page: params[:page])
  end

  def show
    @keyword = @product.title
    Amazon::Ecs.debug = true
    if @keyword.present?
      @res = Amazon::Ecs.item_search(@keyword, :search_index => 'Books', :response_group => 'Medium')
      render layout: "no_side"
    else
      return
      render layout: "no_side"
    end
  end

  def new
    @product = Product.new
  end

  def create
    @product=Product.new(product_params)
    if @product.save
      flash[:success] = "作品の登録に成功しました！"
      redirect_to create_micropost_product_path(@product.id)
    else
      render "new"
    end
  end

  def edit
  end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = "Product updated"
      redirect_to products_url
    else
      render "edit"
    end
  end

  def destroy
    Product.find(params[:id]).destroy
    flash[:success] = "Product destroyed."
    redirect_to products_url
  end

  #マイクロポスト投稿ページ
  def create_micropost
    @micropost = current_user.microposts.build if signed_in?
  end

  #ジャンル別で表示する機能
  # TODO :ジャンル別表示のMVCがなんか冗長だからうまいやりかたを考えること

  def literature
    genre_search("文学・評論")
  end

  def computer
    genre_search("コンピュータ・IT")
  end

  def love
    genre_search("恋愛")
  end

  def history
    genre_search("歴史")
  end

  def mystery
    genre_search("推理")
  end

  def fantasy
    genre_search("ファンタジー")
  end

  def sf
    genre_search("SF")
  end

  def horror
    genre_search("ホラー")
  end

  def comedy
    genre_search("コメディ")
  end

  def adventure
    genre_search("冒険")
  end

  def academy
    genre_search("学園")
  end

  def millitary
    genre_search("戦記")
  end

  def fairy_tail
    genre_search("童話")
  end

  def poem
    genre_search("詩")
  end

  def essay
    genre_search("エッセイ")
  end

  def replay
    genre_search("リプレイ")
  end

  def others
    genre_search("その他")
  end

  def wanna_read
    @product.add_evaluation(:wanna_read, 1, current_user)
    @wanna_read_num = @product.reputation_for(:wanna_read).to_i
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  def not_wanna_read
    @product.delete_evaluation(:wanna_read, current_user)
    @wanna_read_num = @product.reputation_for(:wanna_read).to_i
    respond_to do |format|
      format.html {redirect_to :back}
      format.js
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
      @microposts = @product.microposts.paginate(page: params[:page], :per_page => 10)
    end

    def product_params
      params.require(:product).permit(:id, :title, :genre, :link)
    end

    def genre_search(genre)
      @search = Product.search(:genre_cont => genre)
      @products = @search.result.paginate(page: params[:page])
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_ajax_not_wanna_read.html.haml
= form_tag(not_wanna_read_product_path(@product.id), method: :delete,remote: true) do
  = button_tag( class: "btn btn-white btn-xs dislikes-button", id: @product.id ) do
    = content_tag :span, "読みたいを取消す"

app/views/products/_not_wanna_read.html.haml
= form_tag(not_wanna_read_product_path(product.id), method: :delete,remote: true) do
  = button_tag( class: "btn btn-white btn-xs dislikes-button", id: product.id ) do
    = content_tag :span, "読みたいを取消す"

app/views/products/_search_form.html.haml
#product_search_form
  %h4 作品を検索
  = search_form_for @search do |f|
    .field
      = f.text_field :title_or_genre_cont, placeholder: "（例）  羅生門 タイトル or ジャンル"
    .actions
      = f.submit "検索"

app/views/products/comedy.html.haml
- provide :title, "コメディ作品の一覧"

= render "products/product_index"

app/views/products/essay.html.haml
- provide :title, "エッセイ作品の一覧"

= render "products/product_index"

app/views/products/fairy_tail.html.haml
- provide :title, "童話作品の一覧"

= render "products/product_index"

app/views/products/history.html.haml
- provide :title, "歴史作品の一覧"

= render "products/product_index"

app/views/products/index.html.haml
- provide(:title, '登録作品の一覧')
#product_index_page
  = render "products/search_form"
  = button_to new_product_path, method: :get, class: "btn btn-default new_product_link" do
    %i.glyphicon.glyphicon-plus-sign
    新しく作品を登録する
  .index
    = render "products/product_index"

app/views/products/literature.html.haml
- provide :title, "文学・評論作品の一覧"

= render "products/product_index"

app/views/products/mystery.html.haml
- provide :title, "推理作品の一覧"

= render "products/product_index"

app/views/products/others.html.haml
- provide :title, "その他作品の一覧"

= render "products/product_index"

app/views/products/search_product.html.haml
= provide :title, "感想を投稿（作品を探す）"
%section
  = render "products/search_form"
%section
  .btn.btn-default
    = link_to "新しい作品を追加する", new_product_path

app/views/products/show.html.haml
= provide :title, @product.title
#product_show_page
  .product_info
    - if @res.nil?
      %h2 #{@product.title}
      %span
        ジャンル: #{@product.genre}
      %span
        感想: #{@microposts.count}件
      %span
        URL: 
        = link_to "#{@product.link}", @product.link
      = button_to create_micropost_product_path(@product.id), method: :get, class: "btn btn-default" do
        感想を投稿する
    - else
      - i = @res.items.first
      %h3= i.get('ItemAttributes/Title')
      .image
        = link_to i.get('DetailPageURL')  do
          = image_tag i.get('MediumImage/URL')
      .link
        %h3= link_to "書籍の詳細はこちら", i.get('DetailPageURL') 
      = button_to create_micropost_product_path(@product.id), method: :get, class: "btn btn-default" do
        感想を投稿する
    
  %h4 #{@product.title}に関する感想
  .feed_items
    - if @microposts.any?
      = will_paginate @microposts, :renderer => BootstrapPagination::Rails
      %ol.microposts
        = render partial: "shared/feed_item", collection: @microposts
      = will_paginate @microposts, :renderer => BootstrapPagination::Rails
    - else
      %p
        #{@product.title}の感想はまだありません

app/views/products/wanna_read.js.haml
$(".#{@product.id}.wanna_read_form").html("#{escape_javascript render 'products/ajax_not_wanna_read'}");
$(".#{@product.id}.wanna_read").html('#{@wanna_read_num} 読みたい！');