config/routes.rb
Labohp::Application.routes.draw do
  root "main_pages#home"

  resources :users do
    member do
      get :following, :followers, :activate
    end
    collection do
      get :thanks_for_signup
    end
  end
  match "/introduction", to: "main_pages#introduction", via: "get"
  match "/signup", to: "users#new", via: "get"
  resources :sessions, only: [:new, :create, :destroy]
  match "/signin", to: "sessions#new", via: "get"
  match "/signout", to: "sessions#destroy", via: "delete"
  resources :microposts , only: [:create, :destroy, :edit, :update] do
    member do
      post :likes
      delete :dislikes
    end
  end

  resources :relationships, only: [:create, :destroy]
  
  resources :products do
    collection do
      get :computer, :literature
    end
    
    member do
      get :create_micropost 
      post :wanna_read
      delete :not_wanna_read
    end
  end

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default-white.navbar-fixed-top
  .container
    .row
      / Brand and toggle get grouped for better mobile display
      .navbar-header
        %a.navbar-brand.page-scroll{:href => root_path} Bookstrap!
      / Collect the nav links, forms, and other content for toggling
      %ul.nav.navbar-text.navbar-explanation
        %li 友人や趣味が合う人をフォローして
        %li お気に入りの作品と出会おう
      %ul.nav.navbar-nav.navbar-right
        %li= link_to "TOP", root_path
        %li= link_to "使い方", introduction_path
        %li= link_to "人を探す", users_path
        %li= link_to "作品を探す", products_path
        - if signed_in?
          %li= link_to "新しい作品の追加", new_product_path
          %li#fat-menu.dropdown
            %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
              アカウント管理
              %b.caret
            %ul.dropdown-menu
              %li= link_to "マイページ", current_user
              %li= link_to "ユーザー情報管理", edit_user_path(current_user)
              %li.divider
              %li
                = link_to "ログアウト", signout_path, method: "delete"
        -else
          %li= link_to "ログイン", signin_path
          %li= link_to "会員登録", signup_path
      / /.navbar-collapse
    / /.container-fluid

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= "Bookstrap:#{yield(:title)}"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .container
      - flash.each do |key, value|
        %div(class="alert alert-#{key}")
          = value
    .container#main
      - if signed_in?
        #side-nav.heightLine
          %section#user_info
            = render "shared/user_info"
          %section#user_actions
            = render "shared/user_actions"
          %section#genre_links
            = render "shared/genre_links"
        #home_content.heightLine
          = yield
      - else
        #side-nav.heightLine
          %section#genre_links.not-signedin
            = render "shared/genre_links"
        #home_content.heightLine
          = yield

app/views/layouts/no_side.html.haml
!!!
%html
  %head
    %title= "Bookstrap:#{yield(:title)}"
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    = render "layouts/header"
    .container#no-side
      - flash.each do |key, value|
        %div(class="alert alert-#{key}")
          = value
      .row
        - if signed_in?
          #home_content.col-xs-9.col-md-push-2
            = yield
        - else
          #home_content.col-xs-9.col-md-push-2
            = yield